
// tailwind.config.js
// Generated by Smart Theming Engine
// For integration, merge the 'theme.extend' section into your existing tailwind.config.js

module.exports = {
  content: [
    './*.html', // Adjust this to your project's content files
    './**/*.html',
    './**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#beb2a6',
        secondary: '#d3c6ba',
        accent: '#ffffff',
        // Accessibility Notes (if applicable):
        // [
  {
    "issue": "Primary color contrast with text",
    "context": "Primary background (#beb2a6) vs. text (#ffffff)",
    "current_ratio": 2.08,
    "required_AA": 4.5,
    "suggestion": "Consider adjusting text color to #b2b2b2 or primary background for better contrast.",
    "compliant_AA_normal": false
  },
  {
    "issue": "Secondary color contrast with Primary background",
    "context": "Secondary element (#d3c6ba) on Primary background (#beb2a6)",
    "current_ratio": 1.24,
    "required_AA": 4.5,
    "suggestion": "Consider adjusting secondary color to #bfac9a for better contrast.",
    "compliant_AA_normal": false
  },
  {
    "issue": "Accent color contrast with Primary background",
    "context": "Accent element (#ffffff) on Primary background (#beb2a6)",
    "current_ratio": 2.08,
    "required_AA": 4.5,
    "suggestion": "Consider adjusting accent color to #b2b2b2 for better contrast.",
    "compliant_AA_normal": false
  }
]
      },
      fontFamily: {
        heading: ['Roboto', 'sans-serif'],
        body: ['Open Sans', 'sans-serif'],
      },
      fontSize: {
        xs: '10px',
        sm: '16px',
        base: '16px',
        lg: '26px',
        xl: '42px',
        '2xl': '68px',
        '3xl': '110px',
        '4xl': '177px',
        '5xl': '287px',
      },
      spacing: {
        xs: '6px',
        sm: '10px',
        md: '16px',
        lg: '26px',
        xl: '42px',
      },
    },
  },
  plugins: [],
};
