
// tailwind.config.js
// Generated by Smart Theming Engine
// For integration, merge the 'theme.extend' section into your existing tailwind.config.js

module.exports = {
  content: [
    './*.html', // Adjust this to your project's content files
    './**/*.html',
    './**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#000000',
        secondary: '#102549',
        accent: '#a589a9',
        // Accessibility Notes (if applicable):
        // [
  {
    "issue": "Secondary color contrast with Primary background",
    "context": "Secondary element (#102549) on Primary background (#000000)",
    "current_ratio": 1.38,
    "required_AA": 4.5,
    "suggestion": "Consider adjusting secondary color to #000000 for better contrast.",
    "compliant_AA_normal": false
  }
]
      },
      fontFamily: {
        heading: ['Oswald', 'sans-serif'],
        body: ['Merriweather', 'sans-serif'],
      },
      fontSize: {
        xs: '11px',
        sm: '17px',
        base: '17px',
        lg: '28px',
        xl: '46px',
        '2xl': '74px',
        '3xl': '120px',
        '4xl': '195px',
        '5xl': '316px',
      },
      spacing: {
        xs: '6px',
        sm: '10px',
        md: '16px',
        lg: '26px',
        xl: '42px',
      },
    },
  },
  plugins: [],
};
