
// tailwind.config.js
// Generated by Smart Theming Engine
// For integration, merge the 'theme.extend' section into your existing tailwind.config.js

module.exports = {
  content: [
    './*.html', // Adjust this to your project's content files
    './**/*.html',
    './**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#cbcbcc',
        secondary: '#afb2b9',
        accent: '#090918',
        // Accessibility Notes (if applicable):
        // [
  {
    "issue": "Secondary color contrast with Primary background",
    "context": "Secondary element (#afb2b9) on Primary background (#cbcbcc)",
    "current_ratio": 1.31,
    "required_AA": 4.5,
    "suggestion": "Consider adjusting secondary color to #caccd0 for better contrast.",
    "compliant_AA_normal": false
  },
  {
    "issue": "Accent color contrast with Primary background",
    "context": "Accent element (#b5b5b6) on Primary background (#cbcbcc)",
    "current_ratio": 1.26,
    "required_AA": 4.5,
    "suggestion": "Consider adjusting accent color to #cececf for better contrast.",
    "compliant_AA_normal": false
  }
]
      },
      fontFamily: {
        heading: ['Roboto', 'sans-serif'],
        body: ['Open Sans', 'sans-serif'],
      },
      fontSize: {
        xs: '10px',
        sm: '16px',
        base: '16px',
        lg: '26px',
        xl: '42px',
        '2xl': '68px',
        '3xl': '110px',
        '4xl': '177px',
        '5xl': '287px',
      },
      spacing: {
        xs: '6px',
        sm: '10px',
        md: '16px',
        lg: '26px',
        xl: '42px',
      },
    },
  },
  plugins: [],
};
